# Generated by Django 5.2.2 on 2025-06-07 18:23

from django.db import migrations

#? populates the Role model with initial data.
def populate_role(apps,schemaeditor):
    entries = {
        "developer": "The person on the team who works on issues.",
        "product owner": "The perso who defines issues.",
        "scrum master": "Team's coach.",
    }
    Role = apps.get_model('accounts', 'Role')
    for key,value in entries.items():
        Role_obj = Role(name=key, description=value)
        Role_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_role)  #* Populates the Role model with initial data
    ]
