# Generated by Django 5.2.2 on 2025-06-07 18:23

from django.db import migrations

#? populates the Team model with initial data.
def populate_team(apps,schemaeditor):
    entries = {
        "Sirius": "The Backend team",
        "Vega": "The Frontend team",
        "Altair": "The Mobile apps team"
    }
    Team = apps.get_model('accounts', 'Team')
    for key,value in entries.items():
        Team_obj = Team(name=key, description=value)
        Team_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250607_1123'),
    ]

    operations = [
        migrations.RunPython(populate_team)  #* Populates the Role model with initial data
    ]
